name: Deploy Docker App to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Add SSH private key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Oracle Cloud
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          APP_DIR: ${{ secrets.APP_DIR }}
          GIT_REPO: git@github.com:Alexanderlecky/odoo-18-docker-compose.git
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            set -e
            mkdir -p $APP_DIR
            cd $APP_DIR

            if [ ! -d ".git" ]; then
              git clone $GIT_REPO .
            else
              git pull origin main
            fi

            docker-compose down
            docker-compose build
            docker-compose up -d
          EOF

